notebook:
	python -m notebook \
		--port=8888 \
		--no-browser \
		--ip=0.0.0.0 \
		--notebook-dir=./

daemon:
	Start-Process python -ArgumentList "-m notebook --port=8888 --no-browser --ip=0.0.0.0 --notebook-dir=./" -NoNewWindow
